In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd  # Import the pandas library for data manipulation

df = pd.read_csv('/content/drive/MyDrive/FYP_IIT/IIT_FYP_01.csv', encoding='latin1')
# Read the CSV file from Google Drive into a DataFrame
# encoding='latin1' is used to handle special characters in the dataset

df.head()
# Display the first 5 rows of the DataFrame to preview the data

,Timestamp,What is your gender?,What is your marital status?,Have you ever failed an academic course/module at university?,How satisfied are you with your learning environment at the Faculty?\n,Are you satisfied with your home environment for studying?,What is your Age?,What is your Academic Year?,What is your degree programme.,Competition with my peers for grades is quite intense,...,I have enough time to relax after completing my academic work.,The examination questions are usually difficult.,The allocated examination duration is too short for me to complete my answers properly.,Examination periods are very stressful to me.,I am confident that I will be a successful student.,I am confident that I will be successful in my future career.,I find it easy to make academic decisions.,I fear failing courses/modules this year.,I think that my worry about examinations is weakness of character.,"Even if I pass my exams, I am worried about getting a job"
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2/9/2026 20:38:34,Female, Single, Never,Satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in Business Economics,2.0,...,1.0,2.0,2.0,1.0,2.0,2.0,4.0,2.0,2.0,2.0
2,2/9/2026 20:58:35,Female, Single, Never,Satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in International Business,3.0,...,4.0,3.0,3.0,3.0,2.0,2.0,4.0,2.0,3.0,2.0
3,2/9/2026 21:27:48,Female, Single, Never,Very satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in Human Resource Management,4.0,...,2.0,3.0,3.0,2.0,2.0,3.0,2.0,4.0,5.0,3.0
4,2/10/2026 14:58:19,Male, Single, Once or twice,Satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in Business Economics,2.0,...,1.0,1.0,3.0,4.0,1.0,2.0,3.0,2.0,4.0,3.0

In [3]:
df.shape

(1765, 27)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1765 entries, 0 to 1764
Data columns (total 27 columns):
 #   Column                                                                                                                                      Non-Null Count  Dtype
---  ------                                                                                                                                      --------------  -----
 0   Timestamp                                                                                                                                   1763 non-null   object
 1   What is your gender?                                                                                                                        1763 non-null   object
 2   What is your marital status?                                                                                                                1763 non-null   object
 3   Have you ever failed an academic course/module at university?                                                                               1763 non-null   object
 4   How satisfied are you with your learning environment at the Faculty?
                                                                       1763 non-null   object
 5   Are you satisfied with your home environment for studying?                                                                                  1763 non-null   object
 6   What is your Age?                                                                                                                           1763 non-null   object
 7   What is your Academic Year?                                                                                                                 1763 non-null   object
 8   What is your degree programme.                                                                                                              905 non-null    object
 9   Competition with my peers for grades is quite intense                                                                                       1763 non-null   float64
 10  I feel my lecturers are very strict and often point out mistakes in my work                                                                 1763 non-null   float64
 11  My lecturers expect more from me than I can realistically do.                                                                               1763 non-null   float64
 12  The unrealistic expectations of my parents stress me out.                                                                                   1763 non-null   float64
 13  The time allocated for lectures, laboratory sessions, and independent study is enough for me to manage my academic workload effectively.    1763 non-null   float64
 14  The size of the curriculum (workload) is excessive.                                                                                         1763 non-null   float64
 15  I believe that the amount of work assignments is too much.                                                                                  1763 non-null   float64
 16  I am unable to catch up if I fall behind in my work.                                                                                        1763 non-null   float64
 17  I have enough time to relax after completing my academic work.                                                                              1763 non-null   float64
 18  The examination questions are usually difficult.                                                                                            1763 non-null   float64
 19  The allocated examination duration is too short for me to complete my answers properly.                                                     1763 non-null   float64
 20  Examination periods are very stressful to me.                                                                                               1763 non-null   float64
 21  I am confident that I will be a successful student.                                                                                         1763 non-null   float64
 22  I am confident that I will be successful in my future career.                                                                               1763 non-null   float64
 23  I find it easy to make academic decisions.                                                                                                  1763 non-null   float64
 24  I fear failing courses/modules this year.                                                                                                   1763 non-null   float64
 25  I think that my worry about examinations is weakness of character.                                                                          1763 non-null   float64
 26  Even if I pass my exams, I am worried about getting a job                                                                                   1763 non-null   float64
dtypes: float64(18), object(9)
memory usage: 372.4+ KB

In [5]:
df.dtypes.to_frame(name="Data Type")

                                                   Data Type
Timestamp                                             object
What is your gender?                                  object
What is your marital status?                          object
Have you ever failed an academic course/module ...    object
How satisfied are you with your learning enviro...    object
Are you satisfied with your home environment fo...    object
What is your Age?                                     object
What is your Academic Year?                           object
What is your degree programme.                        object
Competition with my peers for grades is quite i...   float64
I feel my lecturers are very strict and often p...   float64
My lecturers expect more from me than I can rea...   float64
The unrealistic expectations of my parents stre...   float64
The time allocated for lectures, laboratory ses...   float64
The size of the curriculum (workload) is excess...   float64
I believe that the amount of work assignments i...   float64
I am unable to catch up if I fall behind in my ...   float64
I have enough time to relax after completing my...   float64
The examination questions are usually difficult.     float64
The allocated examination duration is too short...   float64
Examination periods are very stressful to me.        float64
I am confident that I will be a successful stud...   float64
I am confident that I will be successful in my ...   float64
I find it easy to make academic decisions.           float64
I fear failing courses/modules this year.            float64
I think that my worry about examinations is wea...   float64
Even if I pass my exams, I am worried about get...   float64

**Data Pre-processing**

In [6]:
df = df.drop(columns=["Timestamp"])

In [7]:
df = df.dropna(how='all')

In [8]:
df.columns = df.columns.str.strip()
# Remove leading and trailing spaces from column names

df.columns = df.columns.str.replace("\n", "", regex=True)
# Remove newline characters (\n) from column names to make them clean and consistent

In [9]:
df.head()

,What is your gender?,What is your marital status?,Have you ever failed an academic course/module at university?,How satisfied are you with your learning environment at the Faculty?,Are you satisfied with your home environment for studying?,What is your Age?,What is your Academic Year?,What is your degree programme.,Competition with my peers for grades is quite intense,I feel my lecturers are very strict and often point out mistakes in my work,...,I have enough time to relax after completing my academic work.,The examination questions are usually difficult.,The allocated examination duration is too short for me to complete my answers properly.,Examination periods are very stressful to me.,I am confident that I will be a successful student.,I am confident that I will be successful in my future career.,I find it easy to make academic decisions.,I fear failing courses/modules this year.,I think that my worry about examinations is weakness of character.,"Even if I pass my exams, I am worried about getting a job"
1,Female, Single, Never,Satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in Business Economics,2.0,3.0,...,1.0,2.0,2.0,1.0,2.0,2.0,4.0,2.0,2.0,2.0
2,Female, Single, Never,Satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in International Business,3.0,4.0,...,4.0,3.0,3.0,3.0,2.0,2.0,4.0,2.0,3.0,2.0
3,Female, Single, Never,Very satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in Human Resource Management,4.0,4.0,...,2.0,3.0,3.0,2.0,2.0,3.0,2.0,4.0,5.0,3.0
4,Male, Single, Once or twice,Satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in Business Economics,2.0,3.0,...,1.0,1.0,3.0,4.0,1.0,2.0,3.0,2.0,4.0,3.0
5,Male, Single, Never,Satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in Business Economics,1.0,2.0,...,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0

In [10]:
df = df.rename(columns={
    'What is your gender?': 'gender',
    'What is your marital status?': 'marital_status',
    'Have you ever failed an academic course/module at university?': 'academic_failure',
    'How satisfied are you with your learning environment at the Faculty?': 'faculty_environment',
    'Are you satisfied with your home environment for studying?': 'home_environment',
    'What is your Age?': 'age_group',
    'What is your Academic Year?': 'academic_year',
    'What is your degree programme.': 'degree_program',
    'Competition with my peers for grades is quite intense': 'peer_competition',
    'I feel my lecturers are very strict and often point out mistakes in my work': 'lecturer_strictness',
    'My lecturers expect more from me than I can realistically do.': 'lecturer_expectations',
    'The unrealistic expectations of my parents stress me out.': 'parental_expectations',
    'The time allocated for lectures, laboratory sessions, and independent study is enough for me to manage my academic workload effectively.': 'time_management',
    'The size of the curriculum (workload) is excessive.': 'curriculum_load',
    'I believe that the amount of work assignments is too much.': 'assignment_load',
    'I am unable to catch up if I fall behind in my work.': 'difficulty_catching_up',
    'I have enough time to relax after completing my academic work.': 'relaxation_time',
    'The examination questions are usually difficult.': 'exam_difficulty',
    'The allocated examination duration is too short for me to complete my answers properly.': 'exam_time_pressure',
    'Examination periods are very stressful to me.': 'exam_stress',
    'I am confident that I will be a successful student.': 'academic_confidence',
    'I am confident that I will be successful in my future career.': 'career_confidence',
    'I find it easy to make academic decisions.': 'decision_making',
    'I fear failing courses/modules this year.': 'module_failure',
    'I think that my worry about examinations is weakness of character.': 'exam_concern',
    'Even if I pass my exams, I am worried about getting a job': 'employment_concern'
})

In [11]:
pd.DataFrame(df.columns, columns=["Column Names"])

              Column Names
0                   gender
1           marital_status
2         academic_failure
3      faculty_environment
4         home_environment
5                age_group
6            academic_year
7           degree_program
8         peer_competition
9      lecturer_strictness
10   lecturer_expectations
11   parental_expectations
12         time_management
13         curriculum_load
14         assignment_load
15  difficulty_catching_up
16         relaxation_time
17         exam_difficulty
18      exam_time_pressure
19             exam_stress
20     academic_confidence
21       career_confidence
22         decision_making
23          module_failure
24            exam_concern
25      employment_concern

In [12]:
reverse_items = [
    "peer_competition",
    "lecturer_strictness",
    "lecturer_expectations",
    "parental_expectations",
    "curriculum_load",
    "assignment_load",
    "difficulty_catching_up",
    "exam_difficulty",
    "exam_time_pressure",
    "exam_stress",
    "module_failure",
    "exam_concern",
    "employment_concern"
]

# Apply reverse coding (1–5 Likert scale)
for col in reverse_items:
    df[col] = 6 - df[col]

In [13]:
df.head()

,gender,marital_status,academic_failure,faculty_environment,home_environment,age_group,academic_year,degree_program,peer_competition,lecturer_strictness,...,relaxation_time,exam_difficulty,exam_time_pressure,exam_stress,academic_confidence,career_confidence,decision_making,module_failure,exam_concern,employment_concern
1,Female, Single, Never,Satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in Business Economics,4.0,3.0,...,1.0,4.0,4.0,5.0,2.0,2.0,4.0,4.0,4.0,4.0
2,Female, Single, Never,Satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in International Business,3.0,2.0,...,4.0,3.0,3.0,3.0,2.0,2.0,4.0,4.0,3.0,4.0
3,Female, Single, Never,Very satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in Human Resource Management,2.0,2.0,...,2.0,3.0,3.0,4.0,2.0,3.0,2.0,2.0,1.0,3.0
4,Male, Single, Once or twice,Satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in Business Economics,4.0,3.0,...,1.0,5.0,3.0,2.0,1.0,2.0,3.0,4.0,2.0,3.0
5,Male, Single, Never,Satisfied, Yes, 2223, Year 4,B.B.A. (Hons) in Business Economics,5.0,4.0,...,2.0,4.0,4.0,4.0,1.0,2.0,1.0,4.0,4.0,5.0

In [14]:
# Columns to clean (remove weird symbols like )
cols_to_clean = [
    "marital_status",
    "academic_failure",
    "home_environment",
    "academic_year"
]
for col in cols_to_clean:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(r"[^\w\s]", "", regex=True)  # remove weird symbols
        .str.strip()
    )
df["age_group"] = (
    df["age_group"]
    .astype(str)
    .str.replace(r"[^\d]", "", regex=True)   # keep only numbers
    .str.replace(r"(\d{2})(\d{2})", r"\1-\2", regex=True)  # insert hyphen
)

In [15]:
df.head()

,gender,marital_status,academic_failure,faculty_environment,home_environment,age_group,academic_year,degree_program,peer_competition,lecturer_strictness,...,relaxation_time,exam_difficulty,exam_time_pressure,exam_stress,academic_confidence,career_confidence,decision_making,module_failure,exam_concern,employment_concern
1,Female,Single,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,4.0,3.0,...,1.0,4.0,4.0,5.0,2.0,2.0,4.0,4.0,4.0,4.0
2,Female,Single,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in International Business,3.0,2.0,...,4.0,3.0,3.0,3.0,2.0,2.0,4.0,4.0,3.0,4.0
3,Female,Single,Never,Very satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Human Resource Management,2.0,2.0,...,2.0,3.0,3.0,4.0,2.0,3.0,2.0,2.0,1.0,3.0
4,Male,Single,Once or twice,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,4.0,3.0,...,1.0,5.0,3.0,2.0,1.0,2.0,3.0,4.0,2.0,3.0
5,Male,Single,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,5.0,4.0,...,2.0,4.0,4.0,4.0,1.0,2.0,1.0,4.0,4.0,5.0

In [16]:
df["degree_program"] = df["degree_program"].str.strip()
df["degree_program"] = df["degree_program"].str.replace(r"\s+", " ", regex=True)

In [17]:
# Fix inconsistent degree program names
df["degree_program"] = df["degree_program"].replace({
    "B.B.A. (Hons) in Hospitality and Leisure Mnagaement": "B.B.A. (Hons) in Hospitality and Leisure Management",
    "B.B.A. (Hons) in Hospitality and Leisure Mnaga...": "B.B.A. (Hons) in Hospitality and Leisure Management"
}, regex=True)

In [18]:
# Standardize using keyword matching
df["degree_program"] = df["degree_program"].str.replace(
    r".*Hospitality and Leisure.*",
    "B.B.A. (Hons) in Hospitality and Leisure Management",
    regex=True
)

In [19]:
# Filter Year 3 and Year 4
year3 = df[df["academic_year"] == "Year 3"]
year4 = df[df["academic_year"] == "Year 4"]

# Count distributions
year3_counts = year3["degree_program"].value_counts().reset_index(name="count")
year3_counts.columns = ["degree_program", "count"]

year4_counts = year4["degree_program"].value_counts().reset_index(name="count")
year4_counts.columns = ["degree_program", "count"]

print("Year 3")
print(year3_counts)

print("\nYear 4")
print(year4_counts)

Year 3
                                      degree_program  count
0                           B.B.A. (Hons) in Finance     90
1                B.B.A. (Hons) in Business Economics     77
2            B.B.A. (Hons) in International Business     67
3                        B.B.A. (Hons) in Accounting     65
4                         B.B.A. (Hons) in Marketing     55
5  B.B.A. (Hons) in Hospitality and Leisure Manag...     40
6           B.B.A. (Hons) in Business Administration     34
7         B.B.A. (Hons) in Human Resource Management     19

Year 4
                                      degree_program  count
0                           B.B.A. (Hons) in Finance     93
1                         B.B.A. (Hons) in Marketing     91
2                B.B.A. (Hons) in Business Economics     61
3            B.B.A. (Hons) in International Business     57
4                        B.B.A. (Hons) in Accounting     54
5           B.B.A. (Hons) in Business Administration     38
6         B.B.A. (Hons) in Human Resource Management     33
7  B.B.A. (Hons) in Hospitality and Leisure Manag...     31

In [20]:
from google.colab import files

# Save final cleaned dataset
df.to_csv("FYP_IIT_cleaned.csv", index=False)

# Download to your computer
files.download("FYP_IIT_cleaned.csv")

In [21]:
df.head()
df.shape

(1763, 26)

**Skewness of datatset**

In [22]:
all_items = [
    'peer_competition','lecturer_strictness','lecturer_expectations','parental_expectations',
    'time_management','curriculum_load','assignment_load','difficulty_catching_up',
    'relaxation_time','exam_difficulty','exam_time_pressure','exam_stress',
    'academic_confidence','career_confidence','decision_making',
    'module_failure','exam_concern','employment_concern'
]

df['overall_stress'] = df[all_items].mean(axis=1)
df['overall_stress'].skew()

np.float64(0.13190747375465614)