In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/FYP_IIT/FYP_IIT_cleaned.csv', encoding='latin1')
df.head()

,gender,marital_status,academic_failure,faculty_environment,home_environment,age_group,academic_year,degree_program,peer_competition,lecturer_strictness,...,relaxation_time,exam_difficulty,exam_time_pressure,exam_stress,academic_confidence,career_confidence,decision_making,module_failure,exam_concern,employment_concern
0,Female,Single,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,4.0,3.0,...,1.0,4.0,4.0,5.0,2.0,2.0,4.0,4.0,4.0,4.0
1,Female,Single,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in International Business,3.0,2.0,...,4.0,3.0,3.0,3.0,2.0,2.0,4.0,4.0,3.0,4.0
2,Female,Single,Never,Very satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Human Resource Management,2.0,2.0,...,2.0,3.0,3.0,4.0,2.0,3.0,2.0,2.0,1.0,3.0
3,Male,Single,Once or twice,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,4.0,3.0,...,1.0,5.0,3.0,2.0,1.0,2.0,3.0,4.0,2.0,3.0
4,Male,Single,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,5.0,4.0,...,2.0,4.0,4.0,4.0,1.0,2.0,1.0,4.0,4.0,5.0

In [3]:
import pandas as pd

# Factor 1
df['F1'] = df[
    ['curriculum_load','assignment_load','difficulty_catching_up',
     'exam_difficulty','exam_time_pressure','exam_stress']
].mean(axis=1)

# Factor 2
df['F2'] = df[
    ['module_failure','exam_concern','employment_concern']
].mean(axis=1)

# Factor 3
df['F3'] = df[
    ['academic_confidence','career_confidence','decision_making','time_management']
].mean(axis=1)

# Factor 4
df['F4'] = df[
    ['lecturer_strictness','lecturer_expectations']
].mean(axis=1)

In [4]:
df.head()

,gender,marital_status,academic_failure,faculty_environment,home_environment,age_group,academic_year,degree_program,peer_competition,lecturer_strictness,...,academic_confidence,career_confidence,decision_making,module_failure,exam_concern,employment_concern,F1,F2,F3,F4
0,Female,Single,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,4.0,3.0,...,2.0,2.0,4.0,4.0,4.0,4.0,3.333333,4.000000,3.00,2.5
1,Female,Single,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in International Business,3.0,2.0,...,2.0,2.0,4.0,4.0,3.0,4.0,3.000000,3.666667,2.75,2.0
2,Female,Single,Never,Very satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Human Resource Management,2.0,2.0,...,2.0,3.0,2.0,2.0,1.0,3.0,3.500000,2.000000,2.00,2.0
3,Male,Single,Once or twice,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,4.0,3.0,...,1.0,2.0,3.0,4.0,2.0,3.0,3.000000,3.000000,2.50,3.0
4,Male,Single,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,5.0,4.0,...,1.0,2.0,1.0,4.0,4.0,5.0,3.833333,4.333333,1.50,4.0

In [5]:
df = df[[
    'gender','academic_failure',
    'faculty_environment','home_environment',
    'age_group','academic_year','degree_program',
    'F1','F2','F3','F4'
]]

In [6]:
df.head()

,gender,academic_failure,faculty_environment,home_environment,age_group,academic_year,degree_program,F1,F2,F3,F4
0,Female,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,3.333333,4.000000,3.00,2.5
1,Female,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in International Business,3.000000,3.666667,2.75,2.0
2,Female,Never,Very satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Human Resource Management,3.500000,2.000000,2.00,2.0
3,Male,Once or twice,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,3.000000,3.000000,2.50,3.0
4,Male,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,3.833333,4.333333,1.50,4.0

In [7]:
df['age_group'] = df['age_group'].astype(str).str.strip()

df['age_group'] = df['age_group'].replace({
    '24-25': '24 and above',
    '24–25': '24 and above',
    'Above 25': '24 and above',
    '25': '24 and above',
    '25 above': '24 and above'
})

In [9]:
df['age_group'] = df['age_group'].replace({
    '24-25': '24 and above',
    'Above 26': '24 and above'
})

In [10]:
df['age_group'].value_counts()

age_group
22-23           816
20-21           613
24 and above    334
Name: count, dtype: int64

In [11]:
df['faculty_environment'] = df['faculty_environment'].astype(str).str.strip()

df['faculty_environment'] = df['faculty_environment'].replace({
    'Dissatisfied': 'Not satisfied',
    'Very dissatisfied': 'Not satisfied'
})

In [12]:
df['faculty_environment'].value_counts()

faculty_environment
Satisfied                             1135
Very satisfied                         283
Neither satisfied nor dissatisfied     271
Not satisfied                           74
Name: count, dtype: int64

In [13]:
df.head()

,gender,academic_failure,faculty_environment,home_environment,age_group,academic_year,degree_program,F1,F2,F3,F4
0,Female,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,3.333333,4.000000,3.00,2.5
1,Female,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in International Business,3.000000,3.666667,2.75,2.0
2,Female,Never,Very satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Human Resource Management,3.500000,2.000000,2.00,2.0
3,Male,Once or twice,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,3.000000,3.000000,2.50,3.0
4,Male,Never,Satisfied,Yes,22-23,Year 4,B.B.A. (Hons) in Business Economics,3.833333,4.333333,1.50,4.0

In [14]:
df['degree_program'] = df['degree_program'].replace({
    'B.B.A. (Hons) in Business Administration': 'Other',
    'B.B.A. (Hons) in Hospitality and Leisure Management': 'Other',
    'B.B.A. (Hons) in Human Resource Management': 'Other'
})

In [15]:
df['degree_program'].value_counts()

degree_program
Other                                      195
B.B.A. (Hons) in Finance                   183
B.B.A. (Hons) in Marketing                 146
B.B.A. (Hons) in Business Economics        138
B.B.A. (Hons) in International Business    124
B.B.A. (Hons) in Accounting                119
Name: count, dtype: int64

In [16]:
# Remove extra spaces and ensure string format
df['degree_program'] = df['degree_program'].astype(str).str.strip()

# Replace empty strings with 'General'
df['degree_program'] = df['degree_program'].replace('', 'General')

# Replace actual NaN values with 'General'
df['degree_program'] = df['degree_program'].replace('nan', 'General')

In [17]:
df['degree_program'].value_counts()

degree_program
General                                    858
Other                                      195
B.B.A. (Hons) in Finance                   183
B.B.A. (Hons) in Marketing                 146
B.B.A. (Hons) in Business Economics        138
B.B.A. (Hons) in International Business    124
B.B.A. (Hons) in Accounting                119
Name: count, dtype: int64

In [18]:
df.dtypes

gender                  object
academic_failure        object
faculty_environment     object
home_environment        object
age_group               object
academic_year           object
degree_program          object
F1                     float64
F2                     float64
F3                     float64
F4                     float64
dtype: object

In [19]:
X = df[[
    'gender','academic_failure','faculty_environment',
    'home_environment','age_group','academic_year','degree_program'
]]

Y = df[['F1','F2','F3','F4']]

In [20]:
df_encoded = pd.get_dummies(df, drop_first=False)

In [21]:
X_encoded = df_encoded.drop(columns=['F1', 'F2', 'F3', 'F4'])
X_encoded.head()
Y.head()

         F1        F2    F3   F4
0  3.333333  4.000000  3.00  2.5
1  3.000000  3.666667  2.75  2.0
2  3.500000  2.000000  2.00  2.0
3  3.000000  3.000000  2.50  3.0
4  3.833333  4.333333  1.50  4.0

In [22]:
final_df = pd.concat([X_encoded, Y], axis=1)

final_df.head()

,gender_Female,gender_Male,academic_failure_Never,academic_failure_Once or twice,academic_failure_Three or more times,faculty_environment_Neither satisfied nor dissatisfied,faculty_environment_Not satisfied,faculty_environment_Satisfied,faculty_environment_Very satisfied,home_environment_No,...,degree_program_B.B.A. (Hons) in Business Economics,degree_program_B.B.A. (Hons) in Finance,degree_program_B.B.A. (Hons) in International Business,degree_program_B.B.A. (Hons) in Marketing,degree_program_General,degree_program_Other,F1,F2,F3,F4
0,True,False,True,False,False,False,False,True,False,False,...,True,False,False,False,False,False,3.333333,4.000000,3.00,2.5
1,True,False,True,False,False,False,False,True,False,False,...,False,False,True,False,False,False,3.000000,3.666667,2.75,2.0
2,True,False,True,False,False,False,False,False,True,False,...,False,False,False,False,False,True,3.500000,2.000000,2.00,2.0
3,False,True,False,True,False,False,False,True,False,False,...,True,False,False,False,False,False,3.000000,3.000000,2.50,3.0
4,False,True,True,False,False,False,False,True,False,False,...,True,False,False,False,False,False,3.833333,4.333333,1.50,4.0

In [23]:
X_encoded = X_encoded.astype(int)

In [24]:
final_df = pd.concat([X_encoded, Y], axis=1)

final_df.head()

,gender_Female,gender_Male,academic_failure_Never,academic_failure_Once or twice,academic_failure_Three or more times,faculty_environment_Neither satisfied nor dissatisfied,faculty_environment_Not satisfied,faculty_environment_Satisfied,faculty_environment_Very satisfied,home_environment_No,...,degree_program_B.B.A. (Hons) in Business Economics,degree_program_B.B.A. (Hons) in Finance,degree_program_B.B.A. (Hons) in International Business,degree_program_B.B.A. (Hons) in Marketing,degree_program_General,degree_program_Other,F1,F2,F3,F4
0,1,0,1,0,0,0,0,1,0,0,...,1,0,0,0,0,0,3.333333,4.000000,3.00,2.5
1,1,0,1,0,0,0,0,1,0,0,...,0,0,1,0,0,0,3.000000,3.666667,2.75,2.0
2,1,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,1,3.500000,2.000000,2.00,2.0
3,0,1,0,1,0,0,0,1,0,0,...,1,0,0,0,0,0,3.000000,3.000000,2.50,3.0
4,0,1,1,0,0,0,0,1,0,0,...,1,0,0,0,0,0,3.833333,4.333333,1.50,4.0

In [25]:
df_encoded.shape

(1763, 29)

In [26]:
df_encoded = df_encoded.apply(
    lambda x: x.astype(int) if x.dtype == 'bool' else x
)

In [27]:
# Save dataset to CSV
df_encoded.to_csv('Prediction_Dataset.csv', index=False)

# Download it
from google.colab import files
files.download('Prediction_Dataset.csv')